### ISSUE TITLE
Fails when firstly opened "RsyncUI > Settings"

### ISSUE THREAD

**Issue by sisungo** [rsyncOSX/RsyncUI#11]
## Environment
```
$ uname -a
Darwin pworks-laptop.local 23.0.0 Darwin Kernel Version 23.0.0: Tue Jul 18 20:35:19 PDT 2023; root:xnu-10002.0.199.505.1~3/RELEASE_ARM64_T8103 arm64

macOS 14.0 Beta (23A5301h) on MacBook Air (M1 chip)
```

## Steps
1. Open `RsyncUI` (which is the "first-time")
2. Select `RsyncUI` from the global menu, then press `Settings`

## Expected behavior
Opens the settings panel

## Actual behavior
An error dialog appears with title `The file "configurations.json" couldn't be opened because there is no such file.` and message `The file doesn't exist`.

**Comment by rsyncOSX** [comment]
The default file errorhandling will throw an error message if file is not found. Please  try to press the save button and the error should go away next time you open the settings panel…

**Comment by rsyncOSX** [comment]
To your info, the issue is fixed in next release, RsyncUI creates default files if not found and error is not issued
