### ISSUE TITLE
RsyncUI Version 1.7.1 (83) using Ventura 13.5.2 (22G91) not working

### ISSUE THREAD

**Issue by transfertroll** [rsyncOSX/RsyncUI#12]
Is anyone having issues with RsyncUI Version 1.7.1 (83) using Ventura 13.5.2 (22G91)?
In Quick Sync, I can execute a dry run but not the actual run.
Remote user and server check marks cant be selected (greyed out)
When I select menu, tasks, execute nothing happens.
![Screenshot 2023-09-20 at 2 58 25 PM](https://github.com/rsyncOSX/RsyncUI/assets/145621052/0e9f0405-e4aa-4d70-8048-297d14ac4da7)

**Comment by rsyncOSX** [comment]
Hi, it seems like you are trying to pull data (syncremote) from a remote server. And quick sync is for not regular tasks, but transferring data if you like have downloaded something and either want to pull it from a server or push it to a server.. 

The Remote user and Remote server only picks up user and servers if there are such data for any regular tasks. If not just add the data manually within the Remote parameters fields. The attached view is pulling data from my local FreeBSD server (backup) to my Mac.. Default dry run to inspect what happens, toggle dry run switch for real run. To execute hit the left arrow in top right corner in menu...

<img width="1412" alt="Screenshot 2023-09-21 at 07 21 42" src="https://github.com/rsyncOSX/RsyncUI/assets/22427340/028f8f21-f3e7-42eb-831f-df8579446294">
