### ISSUE TITLE
Crash if click on left menu items before end of confetti animation

### ISSUE THREAD

**Issue by rivamarco** [rsyncOSX/RsyncUI#15]
Hi, I'm using this tool and I want to highlight this little issue that I have encountered.

System:

Mac mini M1 8/256 with Sonoma 14.2.1
RsyncUI 1.82
rsync 3.2.7

If I click on one of the left menù items (Synchronize, Quick Synchronize, Rsync parameters, ecc...) **before** the end of the confetti animation that we have during the startup, the app crashes.

If I wait, it works correctly without issues.

Dump is attached 

[rsyncui.log](https://github.com/rsyncOSX/RsyncUI/files/13874908/rsyncui.log)

Thank you :)

**Comment by rsyncOSX** [comment]
Hi, thx for reporting. I will investigate.

**Comment by rsyncOSX** [comment]
Well, I managed to crash it myself :-) I will investigate more to see what happens if the user chooses a menu before the confetti stuff is completed... As a workaround just wait until the confetti is completed. The confetti is only presented if you have no tasks saved...

**Comment by rsyncOSX** [comment]
The easy solution is to just remove the confetti from the FirstTime view.. I will check with the developer of the confetti how to abort the confetti before it is complete. If no solution I will just remove the confetti...

**Comment by rsyncOSX** [comment]
I am closing the issue, the confetti is removed and if fixed by the developer it will be introduced again. ..
