### ISSUE TITLE
Unable to sync with working params

### ISSUE THREAD

**Issue by Traace** [rsyncOSX/RsyncUI#16]
1. Run rsync sync via CLI, it works fine :)
2. Using the same parameters in RsyncUI, it never finishes sync or complains that a error happend.

Command that works via CLI but not in RsyncUI:
```/usr/bin/rsync --archive --verbose --compress --delete --password-file /Users/traace/rsync-nas-pw --stats /Users/traace/Documents/ rsync://traace@192.168.3.211/MP1_Storage/RSync/Studio1/Documents/```

Using real rsync daemon as backend, without SSH. MP1_Storage is module location.

**Comment by rsyncOSX** [comment]
well, it is probably not a bug.. but as i can see from the command you are using rsync daemon. A rsync daemon setup is a tweek and requiere some special setup. please see the attached link..

 https://rsyncui.netlify.app/post/rsyncdaemon/

**Comment by rsyncOSX** [comment]
https://rsyncui.netlify.app/post/rsyncparameters/

**Comment by Traace** [comment]
Thanks for your reply and the great explanation.

I wasn't even aware that rsync daemon transfers are unencrypted. Luckily, transfers only happened within the LAN. There is an Open Media Vault based NAS next to me, and the rsync daemon was just so easy to set up.

Anyways, I will switch to an SSH-based connection with keys. It will be safer and is supported by RsyncUI. Therefore, I'm closing this issue 👍
