### ISSUE TITLE
Crash after launch

### ISSUE THREAD

**Issue by Traace** [rsyncOSX/RsyncUI#17]
1. Start RsyncUI
2. Click anything
3. Get a crash report

Sometimes (1/10) it doesn't crash and works. But then it cannot sync at all (see my other issue)

**Comment by rsyncOSX** [comment]
Does it crash when the firstime view and confetti is presented. There is a bug in the confetti, and it is removed from source. The confetti is another open source, not by me…

**Comment by rsyncOSX** [comment]
Anymore details about the crash?

**Comment by Traace** [comment]
It is related to confetti, indeed. I also see that there was a issue opened by another user about this before.

Therefore I'm closing this issue.

Thanks for your support, Thomas :)
