### ISSUE TITLE
Window too wide for my display

### ISSUE THREAD

**Issue by gingerbeardman** [rsyncOSX/RsyncUI#19]
I use a display that is 1200px wide, and the RsyncUI window won't fit as it's 1300px wide.

Any chance it can be made to be more adjustable?

Thanks

**Comment by rsyncOSX** [comment]
Of course I can, min width today is set to 1300 (.frame(minWidth: 1300, minHeight: 510)). I can compile a version min width 1100, and then you can arrange the columns as you want.. I will attach I link here for download in some minutes... It will not be signed, so you need to change the security settings to install it.. I will attach the shamus 256 for you to verify the dmg..

**Comment by rsyncOSX** [comment]
Compiled with min 1100 width, NOT signed (dmg is signed), to install check (change) security in macOS settings when installing.. Please verify the shasum..

https://www.dropbox.com/scl/fi/x0qcqc9mqg6shcjbev7n4/RsyncUI.1.8.8.dmg?rlkey=79rpenyhore3kvekvoolu0ozk&dl=0

shasum -a 256
8c5efa8ced3761eef66ce26a84878929ee1a5d66372eb30b6c96525016b0179b  RsyncUI.1.8.8.dmg

**Comment by gingerbeardman** [comment]
Works for me, many thanks!

**Comment by rsyncOSX** [comment]
Closing issue, deleting the download (safety), you have a copy:-)

**Comment by gingerbeardman** [comment]
My app seems to have been updated, and this narrower window feature is not in the latest release?

**Comment by rsyncOSX** [comment]
I can of course make a special version for you :-) will attach a link to download here in a few min.. Next version will be as you request ...

**Comment by rsyncOSX** [comment]
https://www.dropbox.com/scl/fi/rv579wb36iim0r9quj2up/RsyncUI.1.9.0.dmg?rlkey=vplfd3duri60w73yw7mvxmzi9&dl=0

It is notarised, and shasum 256 is: 61f8d7effb54f7bccb80861b5c6dfb01d1c7252a12a5aded18712be3d062ecca

Next version (1.9.1) will be compiled with width 1100 as requested...

**Comment by rsyncOSX** [comment]
Happy to assist :-) Next official version includes: `.frame(minWidth: 1100, idealWidth: 1300, minHeight: 510)` is updated.. Sorry did not apply in version 1.9.0...
