### ISSUE TITLE
Location Error?

### ISSUE THREAD

**Issue by mykeylynx** [rsyncOSX/RsyncUI#21]
Can you please tell me what parameters to check to get this to work. We can RSYNC ssh to the server. but thought the app I receive the following error. I tried "Shared Drive" and Shared\ Drive thinking it is a space in the file name that may be causing the issue. Installed RSYNC 3 through Brew as well and checked the box. found a thread about downloading the older version but that just freezes.

Thank you.

The operation couldn’t be completed. (RsyncUI.FilesError<RsyncUI.LocationErrorReason> error 1.)

**Comment by mykeylynx** [comment]
Hi Thomas,

Thank yo for your help!
![Screenshot 2024-05-20 at 2 38 42 PM](https://github.com/rsyncOSX/RsyncUI/assets/2422717/4e933554-3828-4a06-b0b5-37ed311fd718)
![Screenshot 2024-05-20 at 2 39 57 PM](https://github.com/rsyncOSX/RsyncUI/assets/2422717/ccf33950-32fd-4cc9-a79d-e37bee6ffd40)

**Comment by rsyncOSX** [comment]
It seems like the parameters are correct. I suggest the following to test the connection to the server:

Select the Rsync Parameters view, select the task and copy the rsync command string below the table, double click on the string and choose copy from the Edit menu: 
<img width="1412" alt="Screenshot 2024-05-20 at 20 51 07" src="https://github.com/rsyncOSX/RsyncUI/assets/22427340/8a2b48b1-842e-4a36-b566-bd74af5c9393">
<img width="1412" alt="Screenshot 2024-05-20 at 20 54 36" src="https://github.com/rsyncOSX/RsyncUI/assets/22427340/48349940-92f4-4ae3-b44a-96ab21b177ce">

Then, open a terminal view and paste the command in the terminal and press enter. If server and ssh is correct, the rsync command should execute with no errors...

<img width="1136" alt="Screenshot 2024-05-20 at 20 55 19" src="https://github.com/rsyncOSX/RsyncUI/assets/22427340/301a59e6-c64a-4fba-a794-db3a30fdfcbb">

**Comment by mykeylynx** [comment]
Thank  you, Thomas, I placed this line in the terminal /opt/homebrew/bin/rsync --archive --verbose --compress --delete -e ssh --dry-run --stats /Users/michael/Downloads/ root@archlinux.local:/Volumes**/Shared Media**/MUSIC/

in shell it worked. in the Rysncui app I tried it and I get an error1

**Comment by mykeylynx** [comment]
Hi Thomas,
I changed my directory to just Shared I tried again still getting the same error. 

Thank you,
Michael

**Comment by rsyncOSX** [comment]
That might rule out the space, something else causes the issue. It might be that the task is actually running, but writing the log can cause the issue.. I suggest the following: 

In the Rsync parameters view, select the task and press the Checker Flag (upper right). This will execute the task, a `--dry-run`.
<img width="1412" alt="Screenshot 2024-05-21 at 06 16 01" src="https://github.com/rsyncOSX/RsyncUI/assets/22427340/7d75b82f-e97d-48a0-af7e-5cfeab87c4ea">
<img width="1412" alt="Screenshot 2024-05-21 at 06 16 11" src="https://github.com/rsyncOSX/RsyncUI/assets/22427340/beec09a5-e4df-4c2f-8598-45d23b44fd55">

**Comment by mykeylynx** [comment]
![Screenshot 2024-05-21 at 12 24 46 AM](https://github.com/rsyncOSX/RsyncUI/assets/2422717/c71daf3f-767f-4776-81ba-7947da5fbbd7)

**Comment by rsyncOSX** [comment]
It is the ssh setup which causes the issue, not RsyncUI. Please verify that ssh by ssh-keys are working. 

From a terminal window try to ssh to your server like this (from /Users/Michael)`ssh root@archlinux.local`. You should log into your server only by ssh-keys, no password...

I have written a short guide for ssh-keys:

https://rsyncui.netlify.app/post/ssh/

**Comment by mykeylynx** [comment]
Thank yo Thomas,
I can login to my server with just a password. It looks like I will have to setup a key pair. I will circle back after. Thanks again!

**Comment by rsyncOSX** [comment]
Ssh by keys are the only way :-) I am closing the issue now. I also advice not to use the root on server, create a normal user. The root is for admin only.
