### ISSUE TITLE
MacOS Sequoia crash

### ISSUE THREAD

**Issue by Cavaliere100** [rsyncOSX/RsyncUI#23]
Just to be sure you known the issue, in Sequoia it starts but then it crashes as soon as you click on Tasks or other menu items.
Sequoia beta 4, MacBook Air M1

**Comment by rsyncOSX** [comment]
Thx for letting me know :-) I have not yet installed Sequoia but will do so in some weeks.

**Comment by rsyncOSX** [comment]
Installing Sequoia on a virtual machine now, will test compiling and running RsyncUI soon on Sequoia.

**Comment by Cavaliere100** [comment]
Wow, that’s a quick reaction! Let me known if I can help anyway

Marco

Il 24 lug 2024, 10:05:37, Thomas Evensen ***@***.***> ha
scritto:

**Comment by rsyncOSX** [comment]
New dmg is compiled on the latest Xcode 16 beta4, the dmg is signed and the app is notarized. The download link is: https://www.dropbox.com/scl/fi/u5t8441w1ymoc9by4pxfu/RsyncUI.2.0.0.dmg?rlkey=aejby4bv14edma1uytar9eejo&st=k7lyjn59&dl=0 

and shasum -a 256 = 26ecd6fde998fec0169e2a86a48ec0cc0e1a80f9d648d331e05a4a5a38638e52

Please let me know when downloaded, I will delete the dmg. There are new features export/import from File menu.. Not yet completed (aka work in progress)...

**Comment by Cavaliere100** [comment]
Will try later, now we are at the beach. I will keep you posted Thks!!  I find your program really usefulMarcoInviato da iPhoneIl giorno 24 lug 2024, alle ore 11:41, Thomas Evensen ***@***.***> ha scritto:﻿
New dmg is compiled on the latest Xcode 16 beta4, the dmg is signed and the app is notarized. The download link is: https://www.dropbox.com/scl/fi/u5t8441w1ymoc9by4pxfu/RsyncUI.2.0.0.dmg?rlkey=aejby4bv14edma1uytar9eejo&st=k7lyjn59&dl=0
and shasum -a 256 = 26ecd6fde998fec0169e2a86a48ec0cc0e1a80f9d648d331e05a4a5a38638e52
Please let me know when downloaded, I will delete the dmg. There are new features export/import from File menu.. Not yet completed (aka work in progress)...

**Comment by rsyncOSX** [comment]
Excellent, I am closing the issue. You can of course still use this version, there will be some development for export and import only. I am using this version myself on a daily basis.

**Comment by Cavaliere100** [comment]
Thks, I find your program really useful, on a daily basis

M.

Il 24 lug 2024, 23:33:47, Thomas Evensen ***@***.***> ha
scritto:
