### ISSUE TITLE
Application hangs if rsync cannot be found

### ISSUE THREAD

**Issue by expiredemulsion** [rsyncOSX/RsyncUI#24]
I have the rsync binary installed at:
/usr/local/bin/
and tried to direct RsyncUI to use that path but upon running or estimating in RsyncUI, I get the message:
"The file "rsync" doesn't exist.
The file doesn't exist."

Then RsyncUI hangs for ever and need to be forcefully terminated.

[RsyncUI crashlog.txt](https://github.com/user-attachments/files/16571943/RsyncUI.crashlog.txt)

rsync  version 3.3.0pre1-7-g2f9b963a  protocol version 31
RsyncUI 2.0.0

**Comment by rsyncOSX** [comment]
I will check it out :-) long time ago since I used other paths than default for rsync. I will check the code now and make an update to solve the issue...

**Comment by rsyncOSX** [comment]
I have discovered why it hangs... I will make an update later this evening, thx for reporting the issue..

**Comment by expiredemulsion** [comment]
Great to hear.
Thanks for such swift correction.

**Comment by rsyncOSX** [comment]
I will make an update for you to test in some hours. I am just about to leave my cabin in the mountains.. It is some hours driving home and I have to verify the changes as well before making a new version for you to test...

**Comment by rsyncOSX** [comment]
Just updated the version 2.0.0 rc. There is a temporary fix for the issue. To reset any wrong values to default values, toggle version of rsync. RsyncUI now starts with no valid rsync in path, and it also shows no valid rsync where rsync version is presented. Thx very much for reporting the issue.

**Comment by expiredemulsion** [comment]
Hello
Do the 2.0.0 b101 build contain the fix?

I'm still getting hangs when trying to open the preferences to change the paths.
The preferences pane opens behind the main screen but the notice about "The file "rsync" doesn't exist." is placed ontop and then the applications hangs.

**Comment by rsyncOSX** [comment]
> Hello Do the 2.0.0 b101 build contain the fix?
> 
> I'm still getting hangs when trying to open the preferences to change the paths. The preferences pane opens behind the main screen but the notice about "The file "rsync" doesn't exist." is placed ontop and then the applications hangs.

That is kind of weird, it should not hang. The reason for hang (previous rc) was because RsyncUI executes a `rsync --version` at startup. I suggest you just delete the settings file, see here where it is: https://rsyncui.netlify.app/post/configfiles/
and restart RsyncUI. RsyncUI then starts with default configs. I have tested the new build for rc 2.0.0 and if I enter a not valid path, it notifies me and starts.

**Comment by rsyncOSX** [comment]
And by toggling the Rsync ver3 in settings, just resets any user settings..
<img width="1070" alt="Screenshot 2024-08-13 at 19 35 55" src="https://github.com/user-attachments/assets/63e73f0e-cdc6-42c6-8fda-66fa7db6ee08">
<img width="356" alt="Screenshot 2024-08-13 at 19 36 11" src="https://github.com/user-attachments/assets/eb63befb-c6b3-4f63-b695-9f896284bda9">
