### ISSUE TITLE
Toggling binary hangs the application

### ISSUE THREAD

**Issue by expiredemulsion** [rsyncOSX/RsyncUI#25]
If the binary selection is toggled after a custom path is set, the application hangs.

1. Install custom rsync binary at /usr/local/bin
2. Open RsyncUI for the first time.
3. Set binary path to /usr/local/bin.
4. This will cause a notice of missing binary pop up time after time. 
5. Finish the entering of the custom path
6. Ensure the save of config is done, check mark green and name of binary shows up in the main window.
7. Rastart RsyncUI and open config.
8. Custom path is now gone.
9. Used binary is back to default.
10. Relaunch RsyncUI and custom binary is back as active.
11. Open prefs and toggle the 3.3 binary selection
12. The warning of missing path is displayed and the RsynUI application hangs.

RsyncUI: 2.0.0. b101
rsync binary path: /usr/local/bin

**Comment by rsyncOSX** [comment]
I am not able to get RsyncUI to hang even with missing path for rsync. The app should not complain when adding path /usr/local/bin if there is a `rsync` file in that catalog. The check for valid rsync is a simple FileManager check if file exists. It is interesting to find out why the app is hanging, it seems like there is some other issue. 

Questions: 
- is the app working as expected with default rsync in `/usr/bin`? 
- do you have Xcode installed and know how to run execute a project in Xcode? 
- if you have Xcode installed (Xcode 16 beta 5) it is very easy to compile and run the app, and Xcode will report any problems like hangs..
