### ISSUE TITLE
German localization for me here in Utah

### ISSUE THREAD

**Issue by mrinella** [rsyncOSX/RsyncUI#3]
I completely appreciate the work you are doing on this app. So thank you. Let me know if there is anything I can provide to help.
<img width="952" alt="Screen Shot 2021-06-30 at 11 53 45 PM" src="https://user-images.githubusercontent.com/193974/124072786-799a2d80-d9fe-11eb-99e4-85a9c7a87b7a.png">

**Comment by rsyncOSX** [comment]
Sorry, there seems to be an issue with localization - don't yet know what causes it. I will make a pure English version for you... ready in five minutes...

**Comment by rsyncOSX** [comment]
Uploaded an English version for you. Thx for reporting the bug... For your info the Big Sur version, which is uploaded, does not include all UI enhancements which RsyncUI for macOS Monterey does.. see [RsyncUI for macOS Montery](https://rsyncui.netlify.app/post/macos12/).

**Comment by rsyncOSX** [comment]
The localization is temporarly disabled.
