### ISSUE TITLE
Older releases?

### ISSUE THREAD

**Issue by bradtchapman** [rsyncOSX/RsyncUI#4]
Please compile the app to be compatible with macOS 10.14+ or make your older releases available.  Most people aren't running macOS Monterey yet, and don't have XCode installed either.

**Comment by rsyncOSX** [comment]
Hi, I would compile a version for Big Sur if possible. The challenge is there are features in code which require MacOS Monterey and Xcode 13, which features can be read about [here (see section about MacOS Monterey](https://rsyncui.netlify.app/post/development/). The features which require MacOS Monterey, are important for the UI too work properly. So, I am sorry to say, the code will not compile on macOS Big Sur.

**Comment by bradtchapman** [comment]
What is the oldest release you have that runs on macos 10.14?  on macos 10.15? etc… it may help to tag those or explain in your readme.md file.

Personally, I am comfortable using rsync in terminal; I’m looking for something to recommend to an end user.  

Thanks,
Brad

—Sent from my iPhone

**Comment by rsyncOSX** [comment]
Hi, you might have a look on RsyncOSX which is compiled for macOS BigSur..
There is also an older version for download, check out the releases for
RsyncOSX..

https://somsubhra.github.io/github-release-stats/?username=rsyncosx&repository=RsyncOSX&page=1&per_page=5

**Comment by rsyncOSX** [comment]
Version 6.5.8 is for older versions of macOS, version 6.6.x is for Big Sur
and never..
