### ISSUE TITLE
No homebrew formula (yet) and status bar problem in dark mode

### ISSUE THREAD

**Issue by estefan3112** [rsyncOSX/RsyncUI#8]
Hi, I really like both of your Rsync apps, and I am just exploring the new app for Monterey. Two questions upfront:

1. Will there be a homebrew cask just like RsyncOSX? It seems to be missing currently.
2. It seems to me that the status bar is very rudimentary when in dark mode - basically a blue dot growing further. Is this intended? 

The blue dot also looks quite funny because it somehow "hangs down" on the right end :-) EDIT: I see, this shall become a circle, sorry for that 👍 

<img width="1126" alt="Bildschirmfoto 2021-12-29 um 21 03 50" src="https://user-images.githubusercontent.com/24915559/147699434-6a96aea0-99b3-4c91-9450-e073597237fe.png">

Many thanks for this, makes rsync jobs so much better!

**Comment by rsyncOSX** [comment]
Hi, thx for your comment.. 

1. I tried to get a home-brew formula for it about 1/2 year ago - was rejected.. I might try again sometime in 2022..
2. The progress bar should be a circle, starting with a dot and 100% when completed.. You might try with more files to transfer, if there are few files the progress bar might jump form a dot to 100% in one go..

**Comment by estefan3112** [comment]
Many thanks. Sorry to hear that.

**Comment by rsyncOSX** [comment]
RsyncUI is a more mature app today - I believe it should be possible to get a home-brew formula for it in 2022...
