### ISSUE TITLE
Just documenting for future reference: kernel panics in Monterey when using SMB shares

### ISSUE THREAD

**Issue by estefan3112** [rsyncOSX/RsyncUI#9]
I just wanted to document this from the CCC website because I am also affected by this:

### Apple's SMB filesystem client causes system stalls, random application crashes, and may lead to kernel panics

We have received several reports (primarily from Apple Silicon Mac users) of unruly macOS behavior that occurs while copying files to an SMB-mounted NAS volume. The behavior includes the following:

- Random application crashes
- Prompts to grant various macOS system services access to the login keychain (i.e. because the service that retains the unlocked keychain reference crashed, thus locking the keychain)
- Laggy mouse behavior
- System stalls that eventually end with a reboot and kernel panic report

Workaround: Users that reported similar trouble on macOS Big Sur reported that using AFP rather than SMB consistently resolved these behaviors

**I also experience this when using rsync in Monterey, both command line and with both of your apps. So I wanted to "warn" you just in case that a user complaint comes in.**

Source: [https://bombich.com/kb/ccc6/macos-monterey-known-issues](https://bombich.com/kb/ccc6/macos-monterey-known-issues)

Ready bo be closed after read.

**Comment by rsyncOSX** [comment]
Hi and thx for notifying me..

**Comment by estefan3112** [comment]
Just updating: Same kernel panic in Monterey 12.2 when syncing over SMB. I was hoping that this bug fix update would resolve this. What a shame.

**Comment by rsyncOSX** [comment]
Hi and thx for letting me know :-) I will try this myself to experience how it is in a few weeks..

**Comment by estefan3112** [comment]
My test scenario: Rsync a larger repository with a lot of single items (several thousands) via SMB to a NAS for the first time. Dry run without issues. Real run also starts normally, but after approx 1 hour of running, the Mac halts and restarts with a kernel panic.
